
public enum EquipmentType {
    [PropertiesDescription("[<Color=white>鞋子</Color>]：出门穿")]
    [PropertiesPartOfbody(PartOfBodyType.Foots)]
    [PropertiesArmament(1)]
    Shoes,//鞋子
    [PropertiesDescription("[<Color=white>长靴</Color>]：看起来腿显长？")]
    [PropertiesPartOfbody(PartOfBodyType.Foots)]
    [PropertiesArmament(2)]
    Boots,//长靴
    [PropertiesDescription("[<Color=white>短裤</Color>]：你确定穿这个冒险？")]
    [PropertiesPartOfbody(PartOfBodyType.LowerPart)]
    [PropertiesArmament(1)]
    Pants,//短裤
    [PropertiesDescription("[<Color=white>长裤</Color>]：至少不怕冷")]
    [PropertiesPartOfbody(PartOfBodyType.LowerPart)]
    [PropertiesArmament(2)]
    Trousers,//长裤
    [PropertiesDescription("[<Color=white>束腰</Color>]：勒的好···紧")]
    [PropertiesPartOfbody(PartOfBodyType.Waist)]
    [PropertiesArmament(1)]
    Waistband,//束腰
    [PropertiesDescription("[<Color=white>腰带</Color>]：腰围变细了耶")]
    [PropertiesPartOfbody(PartOfBodyType.Waist)]
    [PropertiesArmament(2)]
    Belt,//腰带
    [PropertiesDescription("[<Color=white>衬衫</Color>]：风吹过你的白衬衫")]
    [PropertiesPartOfbody(PartOfBodyType.Chest)]
    [PropertiesArmament(1)]
    Shirt,//衬衫
    [PropertiesDescription("[<Color=white>背心</Color>]：假装自己是防弹衣")]
    [PropertiesPartOfbody(PartOfBodyType.Chest)]
    [PropertiesArmament(2)]
    Vest,//背心
    [PropertiesDescription("[<Color=white>外套</Color>]：啊，入秋了")]
    [PropertiesPartOfbody(PartOfBodyType.Shoulder)]
    [PropertiesArmament(1)]
    Coat,//外套
    [PropertiesDescription("[<Color=white>长衫</Color>]：捂得严严实实")]
    [PropertiesPartOfbody(PartOfBodyType.Shoulder)]
    [PropertiesArmament(2)]
    Gown,//长衫            
    [PropertiesDescription("[<Color=white>袖套</Color>]：不怕脏")]
    [PropertiesPartOfbody(PartOfBodyType.Arm)]
    [PropertiesArmament(1)]
    Sleeve,//袖套
    [PropertiesDescription("[<Color=white>手套</Color>]：冻疮是什么鬼")]
    [PropertiesPartOfbody(PartOfBodyType.Hands)]
    [PropertiesArmament(1)]
    Glove, //手套
    [PropertiesDescription("[<Color=white>面罩</Color>]：你看不见我")]
    [PropertiesPartOfbody(PartOfBodyType.Head)]
    [PropertiesArmament(1)]
    Mask,//面罩
    [PropertiesDescription("[<Color=white>头套</Color>]：冷吗？")]
    [PropertiesPartOfbody(PartOfBodyType.Head)]
    [PropertiesArmament(1)]
    Headgear,//头套
}
